version: '2'
services:
    webblog-app:
        image: webblog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webblog-mysql:3306/webblog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    webblog-mysql:
        extends:
            file: mysql.yml
            service: webblog-mysql
